gravatar:
  size1: 50
  size2: 80
  size3: 30
name:
  maximum: 50
email:
  maximum: 255
password:
  minimum: 6
user:
  per_page: 10
  hour_expired: 2
micropost:
  content:
    maximum: 140
  picture:
    maximum: 5
  per_page: 5
image_upload:
  max_width: 400
  max_height: 400
  type: "image/jpeg,image/gif,image/png"
